export {
  CloudTTS,
  cloudTts,
  type TtsPersona,
  type TtsSynthesisOptions,
  type TtsSynthesisResult,
  type TtsUsageState,
  type CloudTTSOptions,
  type CatalogVoice,
  type VoiceValidationResult,
  type VoicePrefs,
  VOICE_CATALOG,
  validateVoiceName,
  familyRank,
  familyFreeAllowance,
  saveVoicePrefs,
  voicePrefsPath,
  loadVoicePrefs,
  voiceFamily,
  languageCodeOf,
  familyPayPerCharNote,
  FREE_VOICE_FAMILIES,
  type CatalogVoiceFamily,
  buildSynthesizeRequest
} from '../plugins/eva-voice/CloudTTS.js';
