export {
  type SttLanguage,
  type SttEncoding,
  type SttOptions,
  type SttResult,
  type SttUsage,
  STT_ENDPOINT,
  STT_PROJECT_HEADER,
  STT_MODEL,
  STT_MONTHLY_CAP_SECONDS,
  STT_TIMEOUT_MS,
  STT_USAGE_PATH,
  monthKey,
  readUsage,
  writeUsage,
  isWithinCap,
  recordUsage,
  resetUsageForTest,
  estimateAudioSeconds,
  probeAudioSeconds,
  buildFfmpegFlacArgs,
  convertToFlac16k,
  buildRecognizeRequest,
  transcribeAudio,
  transcribeVoiceWithFallback
} from '../plugins/eva-voice/CloudSTT.js';
