export {
  EdgeTTS,
  edgeTts,
  type EdgePersona,
  type EdgeSynthesisOptions,
  type EdgeSynthesisResult,
  type EdgeUsageState,
  type EdgeTTSOptions,
  EDGE_TTS_DEFAULT_UK_VOICE,
  EDGE_TTS_DEFAULT_UK_ADAM,
  EDGE_TTS_DEFAULT_RU_VOICE,
  EDGE_TTS_DEFAULT_RU_ADAM,
  EDGE_TTS_DEFAULT_EN_VOICE,
  EDGE_TTS_DEFAULT_EN_ADAM,
  EDGE_TTS_DEFAULT_EVA_VOICE,
  EDGE_TTS_DEFAULT_ADAM_VOICE,
  EDGE_VOICE_CATALOG,
  isEdgeVoice,
  edgeCacheKey
} from '../plugins/eva-voice/EdgeTTS.js';
