export interface ModelPricing {
  inputPer1MTokensUSD: string;
  outputPer1MTokensUSD: string;
  inputPer1MTokensEUR: string;
  outputPer1MTokensEUR: string;
  freeTierStatus: '100% Free Quota Available' | 'Paid / Pay-As-You-Go Only';
  freeTierDetails: string;
}

export interface GeminiModelInfo {
  id: string;
  name: string;
  provider:
    | 'Google DeepMind'
    | 'Anthropic'
    | 'Meta'
    | 'Mistral AI'
    | 'AI21 Labs'
    | 'Cohere'
    | 'DeepSeek'
    | 'OmniRoute'
    | 'OpenRouter'
    | 'OpenCode AI';
  category:
    | 'Google Gemini (Next-Gen)'
    | 'Google Gemini (Long-Context)'
    | 'Google Gemma (Open Weights)'
    | 'Anthropic Claude on Google Cloud'
    | 'Meta Llama 3 on Google Cloud'
    | 'Mistral AI on Google Cloud'
    | 'DeepSeek on Google Cloud'
    | 'AI21 Labs & Cohere on Google Cloud'
    | 'OmniRoute Daemon Cluster'
    | 'OpenRouter Free Models'
    | 'OpenRouter Premium'
    | 'OpenCode Go Platforms';
  description: string;
  contextWindow: number;
  maxOutputTokens: number;
  recommended: boolean;
  tier:
    | 'Free Quota + Paid'
    | 'Vertex AI Enterprise'
    | 'Open Weights'
    | '100% Free Community'
    | 'OmniRoute Daemon'
    | 'OpenCode Platform';
  protocol: 'google-genai' | 'google-vertex' | 'google-partner' | 'openai-compatible';
  pricing: ModelPricing;
}

export const COMPLETE_GOOGLE_MODEL_CATALOG: GeminiModelInfo[] = [
  // ============================================================================
  // 1. GOOGLE GEMINI NEXT-GEN FRONTIER (Google DeepMind - 2026 Fleet)
  // ============================================================================
  {
    id: 'gemini-3.8-flash',
    name: 'Gemini 3.8 Flash',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Frontier ultra-fast autonomous agentic model with native real-time tool orchestration and multi-modal streaming.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: true,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Pro / AI Studio: 15 RPM, 1M TPM, 1,500 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.075 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.300 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.070 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.280 (Paid)',
    },
  },
  {
    id: 'gemini-3.1-pro',
    name: 'Gemini 3.1 Pro',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Premier enterprise reasoning frontier model with 2M token context, deep logic, and architectural planning capability.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: true,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Pro / AI Studio: 2 RPM, 32k TPM, 50 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $1.25 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $5.00 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €1.15 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €4.60 (Paid)',
    },
  },
  {
    id: 'gemini-3.1-flash',
    name: 'Gemini 3.1 Flash',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Lightweight high-efficiency frontier flash model with ultra-low latency inference.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: true,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 15 RPM, 1M TPM ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.050 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.200 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.046 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.185 (Paid)',
    },
  },
  {
    id: 'gemini-2.5-flash',
    name: 'Gemini 2.5 Flash',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Google’s legacy multimodal model.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 15 RPM, 1M TPM, 1,500 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.075 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.30 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.070 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.280 (Paid)',
    },
  },
  {
    id: 'gemini-2.5-pro',
    name: 'Gemini 2.5 Pro',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Legacy analytical reasoning engine.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 2 RPM, 32k TPM, 50 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $1.25 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $5.00 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €1.17 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €4.68 (Paid)',
    },
  },
  {
    id: 'gemini-2.0-flash',
    name: 'Gemini 2.0 Flash',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Next-gen streaming architecture for high-frequency interactive dialogues and agent loops.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 15 RPM, 1M TPM, 1,500 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.10 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.40 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.093 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.375 (Paid)',
    },
  },
  {
    id: 'gemini-2.0-flash-lite',
    name: 'Gemini 2.0 Flash Lite',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Next-Gen)',
    description: 'Ultra cost-efficient model designed for extreme throughput and low latency agent tasks.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 30 RPM, 1,500 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.075 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.30 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.070 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.280 (Paid)',
    },
  },

  // ============================================================================
  // 2. GOOGLE GEMINI LONG-CONTEXT
  // ============================================================================
  {
    id: 'gemini-1.5-pro',
    name: 'Gemini 1.5 Pro',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Long-Context)',
    description: '2,000,000 token context window capable of ingesting entire codebases and long video streams.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 2 RPM, 32k TPM, 50 RPD ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $1.25 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $5.00 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €1.17 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €4.68 (Paid)',
    },
  },
  {
    id: 'gemini-1.5-flash',
    name: 'Gemini 1.5 Flash',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Long-Context)',
    description: 'Fast, lightweight multimodal model with 1,000,000 tokens context.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 15 RPM, 1M TPM ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.075 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.30 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.070 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.280 (Paid)',
    },
  },
  {
    id: 'gemini-1.5-flash-8b',
    name: 'Gemini 1.5 Flash 8B',
    provider: 'Google DeepMind',
    category: 'Google Gemini (Long-Context)',
    description: 'Compact 8-billion parameter version built for high-speed lightweight routing.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Google AI Studio: 15 RPM ($0.00)',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.0375 (Paid)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.15 (Paid)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.035 (Paid)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.140 (Paid)',
    },
  },

  // ============================================================================
  // 3. GOOGLE GEMMA OPEN WEIGHTS (Google DeepMind)
  // ============================================================================
  {
    id: 'gemma-2-27b-it',
    name: 'Gemma 2 (27B Instruct)',
    provider: 'Google DeepMind',
    category: 'Google Gemma (Open Weights)',
    description: 'Google’s flagship open weights model with performance rivaling closed models.',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Open Weights',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Open Weights ($0.00) or Google AI Studio Free Quota',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.27 (Vertex AI)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.27 (Vertex AI)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.25 (Vertex AI)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.25 (Vertex AI)',
    },
  },
  {
    id: 'gemma-2-9b-it',
    name: 'Gemma 2 (9B Instruct)',
    provider: 'Google DeepMind',
    category: 'Google Gemma (Open Weights)',
    description: 'High efficiency open weights model with exceptional reasoning-per-parameter ratio.',
    contextWindow: 8192,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Open Weights',
    protocol: 'google-genai',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Open Weights ($0.00) or Google AI Studio Free Quota',
      inputPer1MTokensUSD: '$0.00 (Free) / $0.10 (Vertex AI)',
      outputPer1MTokensUSD: '$0.00 (Free) / $0.10 (Vertex AI)',
      inputPer1MTokensEUR: '€0.00 (Free) / €0.09 (Vertex AI)',
      outputPer1MTokensEUR: '€0.00 (Free) / €0.09 (Vertex AI)',
    },
  },

  // ============================================================================
  // 4. ANTHROPIC CLAUDE ON GOOGLE CLOUD (Vertex AI Model Garden)
  // ============================================================================
  {
    id: 'claude-3-7-sonnet',
    name: 'Claude 3.7 Sonnet (Vertex AI)',
    provider: 'Anthropic',
    category: 'Anthropic Claude on Google Cloud',
    description: 'Hybrid reasoning and instant response model available on Google Cloud Vertex AI.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud billing per token consumption',
      inputPer1MTokensUSD: '$3.00',
      outputPer1MTokensUSD: '$15.00',
      inputPer1MTokensEUR: '€2.80',
      outputPer1MTokensEUR: '€14.00',
    },
  },
  {
    id: 'claude-3-5-sonnet',
    name: 'Claude 3.5 Sonnet (Vertex AI)',
    provider: 'Anthropic',
    category: 'Anthropic Claude on Google Cloud',
    description: 'Industry benchmark for code generation and multi-step reasoning on Vertex AI.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud billing per token consumption',
      inputPer1MTokensUSD: '$3.00',
      outputPer1MTokensUSD: '$15.00',
      inputPer1MTokensEUR: '€2.80',
      outputPer1MTokensEUR: '€14.00',
    },
  },
  {
    id: 'claude-3-5-haiku',
    name: 'Claude 3.5 Haiku (Vertex AI)',
    provider: 'Anthropic',
    category: 'Anthropic Claude on Google Cloud',
    description: 'High speed, cost-effective Anthropic model running in Google Cloud.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud billing per token consumption',
      inputPer1MTokensUSD: '$0.80',
      outputPer1MTokensUSD: '$4.00',
      inputPer1MTokensEUR: '€0.75',
      outputPer1MTokensEUR: '€3.75',
    },
  },

  // ============================================================================
  // 5. META LLAMA 3 ON GOOGLE CLOUD (Vertex AI Model Garden)
  // ============================================================================
  {
    id: 'llama-3.3-70b-instruct',
    name: 'Meta Llama 3.3 (70B Instruct)',
    provider: 'Meta',
    category: 'Meta Llama 3 on Google Cloud',
    description: 'Meta’s latest 70-billion parameter model fully hosted on Google Cloud Vertex AI.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$0.70',
      outputPer1MTokensUSD: '$0.90',
      inputPer1MTokensEUR: '€0.65',
      outputPer1MTokensEUR: '€0.84',
    },
  },
  {
    id: 'llama-3.2-90b-vision-instruct',
    name: 'Meta Llama 3.2 (90B Vision)',
    provider: 'Meta',
    category: 'Meta Llama 3 on Google Cloud',
    description: 'Premier open multimodal vision and text model on Google Cloud Vertex AI.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$0.90',
      outputPer1MTokensUSD: '$1.20',
      inputPer1MTokensEUR: '€0.84',
      outputPer1MTokensEUR: '€1.12',
    },
  },
  {
    id: 'llama-3.1-405b-instruct',
    name: 'Meta Llama 3.1 (405B Instruct)',
    provider: 'Meta',
    category: 'Meta Llama 3 on Google Cloud',
    description: 'Massive 405-billion parameter frontier model running on Google TPU/GPU cluster.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$3.50',
      outputPer1MTokensUSD: '$3.50',
      inputPer1MTokensEUR: '€3.25',
      outputPer1MTokensEUR: '€3.25',
    },
  },

  // ============================================================================
  // 6. MISTRAL AI ON GOOGLE CLOUD (Vertex AI Model Garden)
  // ============================================================================
  {
    id: 'mistral-large-2411',
    name: 'Mistral Large 2 (Vertex AI)',
    provider: 'Mistral AI',
    category: 'Mistral AI on Google Cloud',
    description: 'Mistral’s top-tier multilingual reasoning and coding model on Google Cloud.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$2.00',
      outputPer1MTokensUSD: '$6.00',
      inputPer1MTokensEUR: '€1.86',
      outputPer1MTokensEUR: '€5.60',
    },
  },
  {
    id: 'codestral-2501',
    name: 'Codestral 25.01 (Vertex AI)',
    provider: 'Mistral AI',
    category: 'Mistral AI on Google Cloud',
    description: 'Specialized code completion, debugging, and fill-in-the-middle on Google Cloud.',
    contextWindow: 256000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$0.30',
      outputPer1MTokensUSD: '$0.90',
      inputPer1MTokensEUR: '€0.28',
      outputPer1MTokensEUR: '€0.84',
    },
  },

  // ============================================================================
  // 7. DEEPSEEK & AI21 ON GOOGLE CLOUD (Vertex AI Model Garden)
  // ============================================================================
  {
    id: 'deepseek-r1',
    name: 'DeepSeek R1 (Reasoning)',
    provider: 'DeepSeek',
    category: 'DeepSeek on Google Cloud',
    description: 'Frontier open reasoning model with transparent chain-of-thought verification on Google Cloud.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Open Weights',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Vertex AI Model Garden compute rate',
      inputPer1MTokensUSD: '$0.55',
      outputPer1MTokensUSD: '$2.19',
      inputPer1MTokensEUR: '€0.51',
      outputPer1MTokensEUR: '€2.04',
    },
  },
  {
    id: 'jamba-1.5-large',
    name: 'AI21 Jamba 1.5 Large',
    provider: 'AI21 Labs',
    category: 'AI21 Labs & Cohere on Google Cloud',
    description: 'Hybrid Mamba-Transformer architecture offering 256,000 tokens long-context speed.',
    contextWindow: 256000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$2.00',
      outputPer1MTokensUSD: '$8.00',
      inputPer1MTokensEUR: '€1.86',
      outputPer1MTokensEUR: '€7.45',
    },
  },
  {
    id: 'command-r-plus',
    name: 'Cohere Command R+',
    provider: 'Cohere',
    category: 'AI21 Labs & Cohere on Google Cloud',
    description: 'Enterprise Retrieval-Augmented Generation (RAG) model on Google Cloud.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Vertex AI Enterprise',
    protocol: 'google-partner',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Google Cloud Vertex AI prediction pricing',
      inputPer1MTokensUSD: '$2.50',
      outputPer1MTokensUSD: '$10.00',
      inputPer1MTokensEUR: '€2.33',
      outputPer1MTokensEUR: '€9.30',
    },
  },

  // ============================================================================
  // 8. OMNIROUTE DAEMON CLUSTER (http://100.66.98.4:20128)
  // LiteLLM-OpenAI-compatible proxy exposing frontier models on local edge.
  // Verified September 2026 free/paid availability.
  // ============================================================================
  {
    id: 'omniroute/gemini-3.8-flash',
    name: 'OmniRoute Gemini 3.8 Flash (Edge Router)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Frontier ultra-fast autonomous agentic model routed via internal OmniRoute daemon cluster.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Direct edge routing via internal daemon cluster ($0.00 margin)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.075 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.300 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.070 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.280 (Upstream)',
    },
  },
  {
    id: 'omniroute/gemini-3.1-pro',
    name: 'OmniRoute Gemini 3.1 Pro (Edge Router)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Premier enterprise reasoning frontier model with 2M context proxied via OmniRoute daemon cluster.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Direct edge routing via internal daemon cluster ($0.00 margin)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted) / $1.25 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted) / $5.00 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted) / €1.15 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted) / €4.60 (Upstream)',
    },
  },
  {
    id: 'omniroute/gemini-2.5-pro',
    name: 'OmniRoute Gemini 2.5 Pro (Edge Router)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'High-availability routing proxy via OmniRoute daemon with automatic load balancing and fallback.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Direct edge routing via internal daemon cluster ($0.00 margin)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted) / $1.25 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted) / $5.00 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted) / €1.17 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted) / €4.68 (Upstream)',
    },
  },
  {
    id: 'omniroute/gemini-2.5-flash',
    name: 'OmniRoute Gemini 2.5 Flash (Edge Router)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Workhorse Google model routed via OmniRoute daemon. Fast, multimodal, 1M context.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: true,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Direct edge routing via internal daemon cluster ($0.00 margin)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.075 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.30 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.070 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.28 (Upstream)',
    },
  },
  {
    id: 'omniroute/gemini-2.0-flash',
    name: 'OmniRoute Gemini 2.0 Flash (Edge Router)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Next-gen streaming architecture routed via OmniRoute for high-frequency interactive dialogues.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Direct edge routing via internal daemon cluster ($0.00 margin)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.10 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted) / $0.40 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.093 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted) / €0.375 (Upstream)',
    },
  },
  {
    id: 'omniroute/deepseek-r1',
    name: 'OmniRoute DeepSeek R1 (Daemon Cluster)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'DeepSeek R1 reasoning executed through local OmniRoute daemon cluster.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.55 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $2.19 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.51 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €2.04 (Upstream)',
    },
  },
  {
    id: 'omniroute/deepseek-v3',
    name: 'OmniRoute DeepSeek V3 (Daemon Cluster)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'DeepSeek V3 671B MoE with extreme cost efficiency and high coding quality routed via OmniRoute.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.14 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $0.28 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.13 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €0.26 (Upstream)',
    },
  },
  {
    id: 'omniroute/llama-3.3-70b',
    name: 'OmniRoute Llama 3.3 70B (Daemon Cluster)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Meta Llama 3.3 70B Instruct open weights routed through OmniRoute daemon cluster.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.59 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $0.79 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.55 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €0.74 (Upstream)',
    },
  },
  {
    id: 'omniroute/qwen-2.5-coder-32b',
    name: 'OmniRoute Qwen 2.5 Coder 32B (Daemon Cluster)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Alibaba Qwen 2.5 Coder 32B code generation specialist routed via OmniRoute.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.18 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $0.18 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.17 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €0.17 (Upstream)',
    },
  },
  {
    id: 'omniroute/mistral-7b',
    name: 'OmniRoute Mistral 7B (Daemon Cluster)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Fast, reliable Mistral 7B lightweight instruction model routed via OmniRoute.',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.05 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $0.05 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.05 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €0.05 (Upstream)',
    },
  },
  {
    id: 'omniroute/gpt-4o',
    name: 'OmniRoute GPT-4o (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI GPT-4o multimodal flagship proxied through OmniRoute daemon gateway.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Edge-routed OpenAI upstream billing',
      inputPer1MTokensUSD: '$2.50',
      outputPer1MTokensUSD: '$10.00',
      inputPer1MTokensEUR: '€2.33',
      outputPer1MTokensEUR: '€9.30',
    },
  },
  {
    id: 'omniroute/gpt-4o-mini',
    name: 'OmniRoute GPT-4o Mini (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI GPT-4o Mini cost-efficient multimodal model proxied via OmniRoute.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.15 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $0.60 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.14 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €0.56 (Upstream)',
    },
  },
  {
    id: 'omniroute/o1',
    name: 'OmniRoute OpenAI o1 (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI o1 advanced reasoning model with chain-of-thought proxied via OmniRoute.',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Edge-routed OpenAI upstream billing',
      inputPer1MTokensUSD: '$15.00',
      outputPer1MTokensUSD: '$60.00',
      inputPer1MTokensEUR: '€14.00',
      outputPer1MTokensEUR: '€55.80',
    },
  },
  {
    id: 'omniroute/o3-mini',
    name: 'OmniRoute OpenAI o3-mini (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI o3-mini fast reasoning model with cost-effective chain-of-thought via OmniRoute.',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $1.10 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $4.40 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €1.02 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €4.09 (Upstream)',
    },
  },
  {
    id: 'omniroute/claude-sonnet-4-5',
    name: 'OmniRoute Claude Sonnet 4.5 (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Anthropic Claude Sonnet 4.5 frontier model proxied through OmniRoute daemon gateway.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Edge-routed Anthropic upstream billing',
      inputPer1MTokensUSD: '$3.00',
      outputPer1MTokensUSD: '$15.00',
      inputPer1MTokensEUR: '€2.80',
      outputPer1MTokensEUR: '€14.00',
    },
  },
  {
    id: 'omniroute/claude-3.5-sonnet',
    name: 'OmniRoute Claude 3.5 Sonnet (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Anthropic Claude 3.5 Sonnet proxied through high-reliability OmniRoute daemon gateway.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Edge-routed Anthropic upstream billing',
      inputPer1MTokensUSD: '$3.00',
      outputPer1MTokensUSD: '$15.00',
      inputPer1MTokensEUR: '€2.80',
      outputPer1MTokensEUR: '€14.00',
    },
  },
  {
    id: 'omniroute/claude-3-5-haiku',
    name: 'OmniRoute Claude 3.5 Haiku (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'High speed, cost-effective Anthropic Claude 3.5 Haiku routed via OmniRoute.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Routed through high-throughput OmniRoute node ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Local) / $0.80 (Upstream)',
      outputPer1MTokensUSD: '$0.00 (Local) / $4.00 (Upstream)',
      inputPer1MTokensEUR: '€0.00 (Local) / €0.75 (Upstream)',
      outputPer1MTokensEUR: '€0.00 (Local) / €3.75 (Upstream)',
    },
  },
  {
    id: 'omniroute/grok-2',
    name: 'OmniRoute Grok 2 (Edge Proxy)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'xAI Grok 2 frontier model with real-time knowledge proxied via OmniRoute.',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'Edge-routed xAI upstream billing',
      inputPer1MTokensUSD: '$2.00',
      outputPer1MTokensUSD: '$10.00',
      inputPer1MTokensEUR: '€1.86',
      outputPer1MTokensEUR: '€9.30',
    },
  },

  // ============================================================================
  // 9. OPENROUTER FREE MODELS (https://openrouter.ai) — September 2026
  // ============================================================================
  {
    id: 'deepseek/deepseek-r1:free',
    name: 'DeepSeek R1 (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Frontier open reasoning model with chain-of-thought verification, 100% free via OpenRouter tier.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'meta-llama/llama-3.3-70b:free',
    name: 'Llama 3.3 70B Instruct (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'State-of-the-art Meta 70B open weight instruction model hosted on OpenRouter free tier.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'google/gemini-2.0-flash-exp:free',
    name: 'Gemini 2.0 Flash Exp (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Ultra-fast Google experimental Gemini 2.0 Flash endpoint accessed via OpenRouter free gateway.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'qwen/qwen-2.5-coder-32b-instruct:free',
    name: 'Qwen 2.5 Coder 32B (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Alibaba Qwen code generation specialist with 128k context on OpenRouter free tier.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'mistralai/mistral-7b-instruct:free',
    name: 'Mistral 7B Instruct (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Fast, reliable 7B lightweight instruction model on OpenRouter free queue.',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'anthropic/claude-3.5-haiku:free',
    name: 'Claude 3.5 Haiku (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Anthropic Claude 3.5 Haiku fast inference model 100% free via OpenRouter community tier.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'google/gemini-3.0-flash:free',
    name: 'Gemini 3.0 Flash (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Google Gemini 3.0 Flash ultra-fast model, 100% free via OpenRouter community tier.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'openai/gpt-4o-mini:free',
    name: 'GPT-4o Mini (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'OpenAI GPT-4o Mini cost-efficient model, 100% free via OpenRouter community tier.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'cognitivecomputations/dolphin3.0-r1-2506:free',
    name: 'Dolphin 3.0 R1 2506 (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Open-source reasoning model Dolphin 3.0 R1 fine-tuned for instruction following, free on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },

  // ============================================================================
  // 9b. OPENROUTER FREE — LIVE-VERIFIED 2026-09-08 (queried /api/v1/models,
  // pricing.prompt == 0 AND pricing.completion == 0). The stale 2025-era
  // ":free" ids above (deepseek-r1:free, gpt-4o-mini:free, …) are PAID on
  // OpenRouter now — runtime fleets must use THIS section.
  // ============================================================================
  {
    id: 'openrouter/free',
    name: 'OpenRouter Free Models Router',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Meta-router that auto-picks any currently-available 100% free OpenRouter model. Never dies from a single model removal — TOP-1 entry choice.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: true,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'nvidia/nemotron-3-ultra-550b-a55b:free',
    name: 'NVIDIA Nemotron 3 Ultra 550B (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Smartest free model of the fleet: NVIDIA Nemotron 3 Ultra 550B MoE (55B active) reasoning, 1M context, free community tier.',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'thinkingmachines/inkling:free',
    name: 'Thinking Machines Inkling (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Thinking Machines flagship with 1M context on OpenRouter free tier.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'thinkingmachines/inkling-small:free',
    name: 'Thinking Machines Inkling Small (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Fast small variant of Inkling, 1M context, free community tier.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'nvidia/nemotron-3-super-120b-a12b:free',
    name: 'NVIDIA Nemotron 3 Super 120B (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'NVIDIA Nemotron 3 Super 120B MoE (12B active), 262k context, free community tier.',
    contextWindow: 262144,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'dots-studio/dots-3-note-preview:free',
    name: 'Dots Studio Dots3-Note Preview (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Dots3-Note 512k-context preview model on OpenRouter free tier.',
    contextWindow: 512000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'google/gemma-4-31b-it:free',
    name: 'Google Gemma 4 31B IT (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Google Gemma 4 31B open-weights instruct via OpenRouter community tier (does NOT consume our Google account).',
    contextWindow: 262144,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'cohere/north-mini-code:free',
    name: 'Cohere North Mini Code (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Cohere North Mini coding specialist, 256k context, free community tier.',
    contextWindow: 256000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'inclusionai/ling-3.0-flash-sante:free',
    name: 'inclusionAI Ling 3.0 Flash Sante (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'inclusionAI Ling 3.0 Flash reasoning model, 262k context, free community tier.',
    contextWindow: 262144,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },
  {
    id: 'poolside/laguna-s-2.1:free',
    name: 'Poolside Laguna S 2.1 (Free on OpenRouter)',
    provider: 'OpenRouter',
    category: 'OpenRouter Free Models',
    description: 'Poolside Laguna S 2.1 code-generation model, 262k context, free community tier.',
    contextWindow: 262144,
    maxOutputTokens: 8192,
    recommended: false,
    tier: '100% Free Community',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter Community Free Tier (20 RPM queue)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },

  // ============================================================================
  // 9c. OMNIROUTE EDGE FLEET (omni/*) — LIVE-VERIFIED 2026-09-08
  // Served by the local LiteLLM daemon :20128 (fixed: prisma client installed).
  // Free self-hosted margin ($0 node fee); auth via LITELLM_MASTER_KEY.
  // ============================================================================
  {
    id: 'omni/cf-gpt-oss-120b',
    name: 'OmniRoute CF GPT-OSS 120B (Cloudflare via edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI GPT-OSS 120B open-weights routed through Cloudflare Workers AI via the local OmniRoute edge daemon.',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Self-hosted edge routing ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted)',
    },
  },
  {
    id: 'omni/cf-llama-3.3-70b',
    name: 'OmniRoute CF Llama 3.3 70B (Cloudflare via edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Meta Llama 3.3 70B Instruct via Cloudflare Workers AI routed by the local OmniRoute edge daemon.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Self-hosted edge routing ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted)',
    },
  },
  {
    id: 'omni/cf-qwen2.5-coder-32b',
    name: 'OmniRoute CF Qwen 2.5 Coder 32B (Cloudflare via edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Alibaba Qwen 2.5 Coder 32B code specialist via Cloudflare Workers AI on the OmniRoute edge.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Self-hosted edge routing ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      outputPer1MTokensUSD: '$0.00 (Self-Hosted)',
      inputPer1MTokensEUR: '€0.00 (Self-Hosted)',
      outputPer1MTokensEUR: '€0.00 (Self-Hosted)',
    },
  },
  {
    id: 'omni/groq-gpt-oss-120b',
    name: 'OmniRoute Groq GPT-OSS 120B (Groq via edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'OpenAI GPT-OSS 120B on Groq LPU ultra-low-latency inference via the OmniRoute edge daemon.',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Groq free tier routed by self-hosted edge ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Groq Free Tier)',
      outputPer1MTokensUSD: '$0.00 (Groq Free Tier)',
      inputPer1MTokensEUR: '€0.00 (Groq Free Tier)',
      outputPer1MTokensEUR: '€0.00 (Groq Free Tier)',
    },
  },
  {
    id: 'omni/zai-glm-5.3-flash',
    name: 'OmniRoute Z.ai GLM 5.3 Flash (edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'Z.ai GLM 5.3 Flash fast frontier model routed by the OmniRoute edge daemon.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'Z.ai free tier routed by self-hosted edge ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (Z.ai Free Tier)',
      outputPer1MTokensUSD: '$0.00 (Z.ai Free Tier)',
      inputPer1MTokensEUR: '€0.00 (Z.ai Free Tier)',
      outputPer1MTokensEUR: '€0.00 (Z.ai Free Tier)',
    },
  },
  {
    id: 'omni/or-nemotron-3-ultra-550b',
    name: 'OmniRoute OR Nemotron 3 Ultra 550B (OpenRouter via edge)',
    provider: 'OmniRoute',
    category: 'OmniRoute Daemon Cluster',
    description: 'NVIDIA Nemotron 3 Ultra 550B MoE routed through OpenRouter free tier by the OmniRoute edge daemon.',
    contextWindow: 1000000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OmniRoute Daemon',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenRouter community free tier routed by self-hosted edge ($0.00 node fee)',
      inputPer1MTokensUSD: '$0.00 (100% Free)',
      outputPer1MTokensUSD: '$0.00 (100% Free)',
      inputPer1MTokensEUR: '€0.00 (100% Free)',
      outputPer1MTokensEUR: '€0.00 (100% Free)',
    },
  },

  // ============================================================================
  // 10. OPENROUTER PREMIUM MODELS — September 2026
  // ============================================================================
  {
    id: 'openai/gpt-4o',
    name: 'GPT-4o (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'OpenAI GPT-4o multimodal flagship with 128k context on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$2.50',
      outputPer1MTokensUSD: '$10.00',
      inputPer1MTokensEUR: '€2.33',
      outputPer1MTokensEUR: '€9.30',
    },
  },
  {
    id: 'openai/gpt-4o-mini',
    name: 'GPT-4o Mini (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'OpenAI GPT-4o Mini cost-efficient multimodal model on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.15',
      outputPer1MTokensUSD: '$0.60',
      inputPer1MTokensEUR: '€0.14',
      outputPer1MTokensEUR: '€0.56',
    },
  },
  {
    id: 'openai/o1-preview',
    name: 'OpenAI o1 Preview (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'OpenAI o1 advanced reasoning model with chain-of-thought on OpenRouter.',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$15.00',
      outputPer1MTokensUSD: '$60.00',
      inputPer1MTokensEUR: '€14.00',
      outputPer1MTokensEUR: '€55.80',
    },
  },
  {
    id: 'openai/o1-mini',
    name: 'OpenAI o1 Mini (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'OpenAI o1 Mini fast reasoning model on OpenRouter.',
    contextWindow: 200000,
    maxOutputTokens: 100000,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$1.10',
      outputPer1MTokensUSD: '$4.40',
      inputPer1MTokensEUR: '€1.02',
      outputPer1MTokensEUR: '€4.09',
    },
  },
  {
    id: 'anthropic/claude-3.5-sonnet',
    name: 'Claude 3.5 Sonnet (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Anthropic Claude 3.5 Sonnet industry-leading code and reasoning model on OpenRouter.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$3.00',
      outputPer1MTokensUSD: '$15.00',
      inputPer1MTokensEUR: '€2.80',
      outputPer1MTokensEUR: '€14.00',
    },
  },
  {
    id: 'anthropic/claude-3-opus',
    name: 'Claude 3 Opus (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Anthropic Claude 3 Opus frontier model for complex reasoning on OpenRouter.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$15.00',
      outputPer1MTokensUSD: '$75.00',
      inputPer1MTokensEUR: '€14.00',
      outputPer1MTokensEUR: '€69.75',
    },
  },
  {
    id: 'google/gemini-2.5-flash',
    name: 'Gemini 2.5 Flash (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Google Gemini 2.5 Flash fast multimodal model on OpenRouter.',
    contextWindow: 1048576,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.075',
      outputPer1MTokensUSD: '$0.30',
      inputPer1MTokensEUR: '€0.070',
      outputPer1MTokensEUR: '€0.28',
    },
  },
  {
    id: 'google/gemini-3.0-pro-exp',
    name: 'Gemini 3.0 Pro Exp (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Google Gemini 3.0 Pro experimental frontier model on OpenRouter.',
    contextWindow: 2097152,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$1.25',
      outputPer1MTokensUSD: '$5.00',
      inputPer1MTokensEUR: '€1.17',
      outputPer1MTokensEUR: '€4.68',
    },
  },
  {
    id: 'deepseek/deepseek-chat-v3-0324',
    name: 'DeepSeek V3 (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'DeepSeek V3 671B MoE model with extreme cost efficiency and high coding quality.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.14',
      outputPer1MTokensUSD: '$0.28',
      inputPer1MTokensEUR: '€0.13',
      outputPer1MTokensEUR: '€0.26',
    },
  },
  {
    id: 'meta-llama/llama-3.1-405b-instruct',
    name: 'Llama 3.1 405B (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Meta Llama 3.1 405B frontier open weights model on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$3.50',
      outputPer1MTokensUSD: '$3.50',
      inputPer1MTokensEUR: '€3.25',
      outputPer1MTokensEUR: '€3.25',
    },
  },
  {
    id: 'mistralai/mistral-large-3',
    name: 'Mistral Large 3 (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Mistral Large 3 top-tier multilingual reasoning and coding model on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 32000,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$2.00',
      outputPer1MTokensUSD: '$6.00',
      inputPer1MTokensEUR: '€1.86',
      outputPer1MTokensEUR: '€5.60',
    },
  },
  {
    id: 'qwen/qwen-2.5-72b-instruct',
    name: 'Qwen 2.5 72B (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Alibaba Qwen 2.5 72B large instruction model on OpenRouter.',
    contextWindow: 32000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.90',
      outputPer1MTokensUSD: '$0.90',
      inputPer1MTokensEUR: '€0.84',
      outputPer1MTokensEUR: '€0.84',
    },
  },
  {
    id: 'x-ai/grok-2',
    name: 'Grok 2 (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'xAI Grok 2 frontier model with real-time knowledge on OpenRouter.',
    contextWindow: 131072,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$2.00',
      outputPer1MTokensUSD: '$10.00',
      inputPer1MTokensEUR: '€1.86',
      outputPer1MTokensEUR: '€9.30',
    },
  },
  {
    id: 'perplexity/llama-3.1-sonar-405b-instruct',
    name: 'Perplexity Sonar 405B (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'Perplexity Llama 3.1 Sonar 405B with real-time web search integration on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$3.50',
      outputPer1MTokensUSD: '$14.00',
      inputPer1MTokensEUR: '€3.25',
      outputPer1MTokensEUR: '€13.00',
    },
  },
  {
    id: 'nvidia/llama-3.1-nemotron-70b-instruct',
    name: 'NVIDIA Nemotron 70B (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'NVIDIA NeMo Nemotron 70B RLHF-optimized instruction model on OpenRouter.',
    contextWindow: 128000,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.59',
      outputPer1MTokensUSD: '$0.79',
      inputPer1MTokensEUR: '€0.55',
      outputPer1MTokensEUR: '€0.74',
    },
  },
  {
    id: 'deepseek/deepseek-r1',
    name: 'DeepSeek R1 (OpenRouter Premium)',
    provider: 'OpenRouter',
    category: 'OpenRouter Premium',
    description: 'DeepSeek R1 reasoning model on OpenRouter (higher limits than free tier).',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'Free Quota + Paid',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: 'Paid / Pay-As-You-Go Only',
      freeTierDetails: 'OpenRouter credit balance',
      inputPer1MTokensUSD: '$0.55',
      outputPer1MTokensUSD: '$2.19',
      inputPer1MTokensEUR: '€0.51',
      outputPer1MTokensEUR: '€2.04',
    },
  },

  // ============================================================================
  // 11. OPENCODE GO PLATFORMS (OpenCode AI Platform API / OmniRoute Adapter)
  // Same local edge endpoint as OmniRoute: http://100.66.98.4:20128/v1
  // All "opencode/" models are code-specialized variants.
  // ============================================================================
  {
    id: 'opencode/go-coder-32b',
    name: 'OpenCode Go Coder 32B',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Specialized enterprise coding platform model with automated unit test generation and refactoring.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.20 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.60 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.18 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.55 (Prod)',
    },
  },
  {
    id: 'opencode/go-fast',
    name: 'OpenCode Go Fast (Low-Latency)',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Ultra-low latency code agent model optimized for autocomplete and fast interactive edits.',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.08 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.24 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.07 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.22 (Prod)',
    },
  },
  {
    id: 'opencode/zen-coder-pro',
    name: 'OpenCode Zen Coder Pro',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Zen-grade enterprise coding model with multi-language refactoring, AST analysis, and security audit. Pro tier with deeper reasoning.',
    contextWindow: 128000,
    maxOutputTokens: 16384,
    recommended: true,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.40 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $1.20 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.37 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €1.12 (Prod)',
    },
  },
  {
    id: 'opencode/zen-fast-7b',
    name: 'OpenCode Zen Fast 7B (Edge Coder)',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Lightweight 7B Zen-fast edge coder optimized for IDE autocomplete and inline refactoring at sub-100ms latency.',
    contextWindow: 32768,
    maxOutputTokens: 4096,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.04 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.12 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.04 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.11 (Prod)',
    },
  },
  {
    id: 'opencode/zen-reasoner-32b',
    name: 'OpenCode Zen Reasoner 32B',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Deep chain-of-thought reasoning coder for complex algorithms, architectural refactors, and bug forensics.',
    contextWindow: 128000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.30 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.90 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.28 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.84 (Prod)',
    },
  },
  {
    id: 'opencode/zen-multi-lang-70b',
    name: 'OpenCode Zen Multi-Lang 70B',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: '70B frontier code model supporting 100+ languages with deep context and CI/CD-grade refactoring.',
    contextWindow: 200000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.60 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $1.80 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.56 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €1.67 (Prod)',
    },
  },
  {
    id: 'opencode/zen-security-auditor',
    name: 'OpenCode Zen Security Auditor',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Specialized security audit coder trained on OWASP Top 10, CVE database, and zero-trust patterns.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.35 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $1.05 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.33 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.98 (Prod)',
    },
  },
  {
    id: 'opencode/zen-test-gen',
    name: 'OpenCode Zen Test Generator',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Automated unit test and integration test generation. Supports Jest, pytest, JUnit, Go test frameworks.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.25 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.75 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.23 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.70 (Prod)',
    },
  },
  {
    id: 'opencode/zen-docs-writer',
    name: 'OpenCode Zen Docs Writer',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Technical documentation generator producing JSDoc, OpenAPI specs, README files, and architecture diagrams.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.18 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.54 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.17 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.50 (Prod)',
    },
  },
  {
    id: 'opencode/zen-frontend-react',
    name: 'OpenCode Zen Frontend (React/Next.js)',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Frontend specialist for React 19, Next.js 15, TypeScript, Tailwind CSS, and component architecture.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.22 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.66 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.20 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.61 (Prod)',
    },
  },
  {
    id: 'opencode/zen-backend-go',
    name: 'OpenCode Zen Backend (Go/Rust)',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'Backend systems specialist for Go, Rust, gRPC, microservices, and high-throughput APIs.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.22 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.66 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.20 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.61 (Prod)',
    },
  },
  {
    id: 'opencode/zen-devops-k8s',
    name: 'OpenCode Zen DevOps (K8s/Terraform)',
    provider: 'OpenCode AI',
    category: 'OpenCode Go Platforms',
    description: 'DevOps and SRE specialist for Kubernetes manifests, Terraform modules, Helm charts, and CI/CD pipelines.',
    contextWindow: 64000,
    maxOutputTokens: 8192,
    recommended: false,
    tier: 'OpenCode Platform',
    protocol: 'openai-compatible',
    pricing: {
      freeTierStatus: '100% Free Quota Available',
      freeTierDetails: 'OpenCode Zen Developer Community Quota',
      inputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.28 (Prod)',
      outputPer1MTokensUSD: '$0.00 (Dev Tier) / $0.84 (Prod)',
      inputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.26 (Prod)',
      outputPer1MTokensEUR: '€0.00 (Dev Tier) / €0.78 (Prod)',
    },
  },
];

export const GEMINI_MODELS = COMPLETE_GOOGLE_MODEL_CATALOG;

export class ModelRegistry {
  public static getAllModels(): GeminiModelInfo[] {
    return [...COMPLETE_GOOGLE_MODEL_CATALOG];
  }

  public static getModelById(id: string): GeminiModelInfo | undefined {
    return COMPLETE_GOOGLE_MODEL_CATALOG.find((m) => m.id === id);
  }

  public static isValidModel(id: string): boolean {
    return COMPLETE_GOOGLE_MODEL_CATALOG.some((m) => m.id === id);
  }

  public static getDefaultModel(): GeminiModelInfo {
    return COMPLETE_GOOGLE_MODEL_CATALOG.find((m) => m.recommended) || COMPLETE_GOOGLE_MODEL_CATALOG[0];
  }

  public static getCategories(): string[] {
    const cats = new Set(COMPLETE_GOOGLE_MODEL_CATALOG.map((m) => m.category));
    return Array.from(cats);
  }

  public static getModelsByCategory(category: string): GeminiModelInfo[] {
    return COMPLETE_GOOGLE_MODEL_CATALOG.filter((m) => m.category === category);
  }

  public static getFreeModels(): GeminiModelInfo[] {
    return COMPLETE_GOOGLE_MODEL_CATALOG.filter((m) => m.pricing.freeTierStatus === '100% Free Quota Available');
  }

  public static getPaidOnlyModels(): GeminiModelInfo[] {
    return COMPLETE_GOOGLE_MODEL_CATALOG.filter((m) => m.pricing.freeTierStatus === 'Paid / Pay-As-You-Go Only');
  }

  public static getTop10FreeModels(): GeminiModelInfo[] {
    return this.getFreeModels().slice(0, 10);
  }

  public static getTop10PaidSmartestModels(): GeminiModelInfo[] {
    return this.getPaidOnlyModels().slice(0, 10);
  }

  public static estimateTokens(text: string): number {
    if (!text) return 0;
    return Math.ceil(text.length / 4);
  }

  public static calculateCost(
    modelId: string,
    promptTokens: number,
    completionTokens: number,
  ): TokenCostEstimate {
    const model = this.getModelById(modelId);
    if (!model) {
      return { inputCost: 0, outputCost: 0, totalCost: 0, currency: 'USD', costUSD: 0, costEUR: 0 };
    }

    const inputPriceStr = model.pricing.inputPer1MTokensUSD;
    const outputPriceStr = model.pricing.outputPer1MTokensUSD;
    const inputPriceEurStr = model.pricing.inputPer1MTokensEUR;
    const outputPriceEurStr = model.pricing.outputPer1MTokensEUR;

    const inputRateUSD = this.parsePrice(inputPriceStr);
    const outputRateUSD = this.parsePrice(outputPriceStr);
    const inputRateEUR = this.parsePrice(inputPriceEurStr);
    const outputRateEUR = this.parsePrice(outputPriceEurStr);

    const costUSD = (promptTokens / 1_000_000) * inputRateUSD + (completionTokens / 1_000_000) * outputRateUSD;
    const costEUR = (promptTokens / 1_000_000) * inputRateEUR + (completionTokens / 1_000_000) * outputRateEUR;

    return {
      inputCost: (promptTokens / 1_000_000) * inputRateUSD,
      outputCost: (completionTokens / 1_000_000) * outputRateUSD,
      totalCost: costUSD,
      currency: 'USD',
      costUSD,
      costEUR,
    };
  }

  private static parsePrice(priceStr: string): number {
    const match = priceStr.match(/\$([\d.]+)/);
    if (match) return parseFloat(match[1]);
    const eurMatch = priceStr.match(/€([\d.]+)/);
    if (eurMatch) return parseFloat(eurMatch[1]);
    return 0;
  }
}

export interface TokenCostEstimate {
  inputCost: number;
  outputCost: number;
  totalCost: number;
  currency: 'USD' | 'EUR';
  costUSD: number;
  costEUR: number;
}
